/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mihirjoshi_ocr_ImageProcessingActivity */

#ifndef _Included_com_mihirjoshi_ocr_ImageProcessingActivity
#define _Included_com_mihirjoshi_ocr_ImageProcessingActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mihirjoshi_ocr_ImageProcessingActivity_STEPS
#define com_mihirjoshi_ocr_ImageProcessingActivity_STEPS 5L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_GET_IMAGE
#define com_mihirjoshi_ocr_ImageProcessingActivity_GET_IMAGE 100L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_MAGIC_COLOR
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_MAGIC_COLOR 101L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_GRAY_MODE
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_GRAY_MODE 102L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_BW
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_BW 103L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_MIRROR
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_MIRROR 104L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_ANTICLOCKWISE
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_ANTICLOCKWISE 105L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_CLOCKWISE
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_CLOCKWISE 106L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_ORIGINAL
#define com_mihirjoshi_ocr_ImageProcessingActivity_EFFECT_ORIGINAL 107L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_ACTIVITY_CAMERA
#define com_mihirjoshi_ocr_ImageProcessingActivity_ACTIVITY_CAMERA 1001L
#undef com_mihirjoshi_ocr_ImageProcessingActivity_ACTIVITY_FILE
#define com_mihirjoshi_ocr_ImageProcessingActivity_ACTIVITY_FILE 1002L
/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getText
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getScannedBitmap
 * Signature: (Landroid/graphics/Bitmap;FFFFFFFF)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getScannedBitmap
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getGrayBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getGrayBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getMagicColorBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getMagicColorBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getBAndWBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getBAndWBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getMirrorBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getMirrorBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getFlipRightBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getFlipRightBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getFlipLeftBitmap
 * Signature: (Landroid/graphics/Bitmap;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getFlipLeftBitmap
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getBitmapsForOcr
 * Signature: (Landroid/graphics/Bitmap;)[Landroid/graphics/Bitmap;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getBitmapsForOcr
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mihirjoshi_ocr_ImageProcessingActivity
 * Method:    getPoints
 * Signature: (Landroid/graphics/Bitmap;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mihirjoshi_ocr_ImageProcessingActivity_getPoints
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
